// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnypnkdjhelvbbfzcabg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBueXBua2RqaGVsdmJiZnpjYWJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzI1NzAsImV4cCI6MjA3Mjc0ODU3MH0.PaaSb81z5tz4Z1p8yyFY8JiLowHeNXjmclviB2HYyQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});